services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ../.env.dev
    hostname: localhost
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  back_dev:
    build:
      context: ../
      dockerfile: ./.dev/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/back_dev
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
