name: Backend workflows
on:
  push:
    branches-ignore:
      - ignore/**
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create .env file needed
        run: |
          echo "System.put_env(\"SECRET_KEY_BASE\", \"${{ secrets.SECRET_KEY_BASE }}\")" > .env.dev.exs
          echo "System.put_env(\"DATABASE_URL\", \"${{ secrets.DATABASE_URL }}\")" >> .env.dev.exs
          echo "System.put_env(\"DB_USER\", \"${{ secrets.DB_USER }}\")" >> .env.dev.exs
          echo "System.put_env(\"DB_PASSWORD\", \"${{ secrets.DB_PASSWORD }}\")" >> .env.dev.exs
          echo "System.put_env(\"DB_NAME\", \"${{ secrets.DB_NAME }}\")" >> .env.dev.exs
          echo "System.put_env(\"DB_HOST\", \"${{ secrets.DB_HOST }}\")" >> .env.dev.exs
          echo "System.put_env(\"DB_PORT\", \"${{ secrets.DB_PORT }}\")" >> .env.dev.exs
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.18"
      - name: Install dependencies
        run: |
          elixir --version
          mix local.hex --force # needed to get phoenix
          mix local.rebar --force # for telemetry
          mix deps.get
          # mix setup # should install dependencies and set migrations
      - name: Check coding style
        run: mix format --check-formatted
      - name: Check if can compile
        run: mix compile
      # - name: Run tests
      #   run: mix test
