name: Backend workflows
on:
  push:
    branches-ignore:
      - ignore/**
  pull_request:
    branches-ignore:
      - ignore/**

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install necessary packages
        run: |
          sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
          sudo apt-get update -qq
          sudo apt-get install -y elixir erlang-dev erlang-xmerl
          elixir --version
      - name: Run tests
        run: mix test
