name: Backend workflows
on:
  push:
    branches-ignore:
      - ignore/**
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: elixir erlang-dev erlang-xmerl
          version: 1.0
      - name: Install dependencies
        run: |
          # mix local.hex --force
          # mix deps.get
          mix setup # should install dependencies and set migrations
      - name: Check coding style
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
