name: Backend workflows
on:
  push:
    branches-ignore:
      - ignore/**
  pull_request:
    branches-ignore:
      - ignore/**

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '27'
          elixir-version: '1.17.1'
      - name: Run tests
        run: mix test
